In [1]:
import numpy as np

# Shaping Arrays

In [10]:
d = np.zeros([2, 3], dtype=float)
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
d = np.ones([3, 3], dtype=int)
d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
f = np.random.rand(5, 3)
f

array([[0.35696878, 0.25066932, 0.81645587],
       [0.31776597, 0.74143919, 0.98294361],
       [0.9252383 , 0.80647946, 0.29657284],
       [0.07139936, 0.59148919, 0.93667888],
       [0.26525747, 0.19336058, 0.83268609]])

In [16]:
g = np.full((2,2), 10)
g

array([[10, 10],
       [10, 10]])

In [ ]:
h = np.full((2, 2, 3), [1,])