In [2]:
import numpy as np

# Shaping Arrays

In [10]:
d = np.zeros([2, 3], dtype=float)
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
d = np.ones([3, 3], dtype=int)
d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
f = np.random.rand(5, 3)
f

array([[0.35696878, 0.25066932, 0.81645587],
       [0.31776597, 0.74143919, 0.98294361],
       [0.9252383 , 0.80647946, 0.29657284],
       [0.07139936, 0.59148919, 0.93667888],
       [0.26525747, 0.19336058, 0.83268609]])

In [16]:
g = np.full((2,2), 10)
g

array([[10, 10],
       [10, 10]])

In [18]:
h = np.full((2, 2, 3), [1, 2, 3])
h

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

# Sequences

In [20]:
a = np.arange(10, 50, 2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [21]:
b = np.linspace(10, 50, 15)
np.lin
b

array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714, 30.        , 32.85714286, 35.71428571,
       38.57142857, 41.42857143, 44.28571429, 47.14285714, 50.        ])

# Element-wise operations

In [33]:
a = np.array([1, 4, 6, 8])
b = np.array([1, 1, 1, 1])

In [34]:
c = a - b
c

array([0, 3, 5, 7])

In [35]:
d = a * b
d

array([1, 4, 6, 8])

In [38]:
fahrenheit = np.array([0, -5, -10])
celsius = (fahrenheit - 31) * (5/9)
celsius

array([-17.22222222, -20.        , -22.77777778])

In [39]:
celsius >= -20

array([ True,  True, False])

# Arange function with reshape function

In [40]:
np.arange(1, 16, 1).reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
np.arange(6, 58, 3).reshape(3, 6)

array([[ 6,  9, 12, 15, 18, 21],
       [24, 27, 30, 33, 36, 39],
       [42, 45, 48, 51, 54, 57]])

# Numpy indexing

In [46]:
a = np.array([[1, 2, 33], [4, 5, 6], [7, 8, 9]])
a[0][0]

1

In [47]:
print(a[a > 5])

[33  6  7  8  9]


# Numpy slicing

In [49]:
a = np.array([1, 2, 5, 7, 8])

In [50]:
a[:2]

array([1, 2])

In [51]:
a[2:4]

array([5, 7])

In [52]:
a = np.array([[1, 2, 33], [4, 5, 6], [7, 8, 9]])
a[1:2, 1:3]

array([[5, 6]])

# Deleting

In [57]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr.ndim

2

In [60]:
# Deletes specificed elements and flattens
np.delete(arr, [0, 1])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
# axis = 0 for deletion of rows, axis = 1 for deletion of columns
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.delete(arr, [2, 3], axis = 1) # getting rid of 3rd and 4th columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [62]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.delete(arr, [0, 1], axis = 0) # getting rid of 1st and 2nd rows

array([[ 9, 10, 11, 12]])

# Appending

In [64]:
np.append([(5, 9, 13, 15), (19, 23, 27, 29), (32, 36, 37, 39), (43, 45, 56, 67)], 0)

array([ 5,  9, 13, 15, 19, 23, 27, 29, 32, 36, 37, 39, 43, 45, 56, 67,  0])

# Insert

In [81]:
a = np.array([[1, 1], [2, 2], [3, 3]])

In [75]:
a.ndim

2

In [76]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [77]:
np.insert(a, 3, 5, axis = 0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [5, 5]])

In [78]:
np.insert(a, 0, 5, axis = 1)

array([[5, 1, 1],
       [5, 2, 2],
       [5, 3, 3]])

In [82]:
# Place both the 5 and 6 in the second index positions, one right after another
np.insert(a, [2, 2], [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

# Reshape -1

In [84]:
b = np.arange(8)
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [87]:
b = np.reshape(b, [2, 4])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
b.shape

(2, 4)

In [91]:
# One way to do it
b = b.reshape(-1, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
# Another way to do it
b = np.reshape(b, [-1, 4])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [94]:
b = b.reshape(2, -1)

In [95]:
b = b.reshape(4, -1)

# Transpose

In [98]:
t = np.array([5, 6, 7])
t

array([5, 6, 7])

In [99]:
t.ndim

1

In [101]:
t = t.transpose()
t

array([5, 6, 7])

In [103]:
t = np.arange(20).reshape(4, -1)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [104]:
t.ndim

2

In [107]:
t = t.transpose()
t

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Concatenate

In [114]:
# Concatenating rows
a = np.array([[1, 2], [3, 4]])
# Must have same dimension - which is 2
b = np.array([[5, 6]])

In [118]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
# Doesn't work concatenating columns (axis = 1) because ...
# index 0    1, 2, 5, 6
# index 1    3, 4
np.concatenate((a, b), axis = 1)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [122]:
# But this works
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [125]:
# And this also works
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.transpose()), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [126]:
# And this also works
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.transpose()), axis = None)

array([1, 2, 3, 4, 5, 6])

# Splitting

In [3]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b = np.split(a, 3)
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [5]:
b = np.split(a, [4, 7])
b

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [6]:
b = np.split(a, 4)
b

ValueError: array split does not result in an equal division

In [8]:
b = np.array_split(a, 4)
b

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

# Aggregate/statistical functions

In [9]:
arr = np.array([[10, 15, 24], [43, 47, 62]])
arr

array([[10, 15, 24],
       [43, 47, 62]])

In [10]:
np.mean(arr)

33.5

In [11]:
np.var(arr)

344.9166666666667

In [12]:
np.mean(arr, axis = 1)

array([16.33333333, 50.66666667])

In [13]:
np.sum(arr, axis = 1)

array([ 49, 152])

In [14]:
np.prod(arr, axis = 1)

array([  3600, 125302])

In [15]:
arr = np.array([[10, 15, 24], [43, 47, 62]])
np.cumsum(arr, axis = 1)


array([[ 10,  25,  49],
       [ 43,  90, 152]])

In [16]:
np.cumprod(arr, axis = 1)

array([[    10,    150,   3600],
       [    43,   2021, 125302]])

In [22]:
arr = np.array([[10, 15, 1, 24], [43, 47, 62, 2]])
np.argmin(arr, axis = 1)

array([2, 3])